---
driver:
  name: vagrant
  customize:
    memory: 1024

verifier:
  name: inspec

provisioner:
  name: chef_zero
  product_name: chef
  chef_license: accept-no-persist
  deprecations_as_errors: true

platforms:
  - name: centos-7
    driver:
      box: centos/7 # virtualbox, vmware, parallels
      image: centos-7-0-x64 # digitalocean

  - name: ubuntu-20.04
    driver:
      box: bento/ubuntu-20.04
      image: ubuntu-20-04-x64
    attributes:
      nginx:
        install_method: source

suites:
- name: http
  run_list:
    - recipe[acme_server]
    - recipe[acme_client::http]
  attributes:
    acme:
      dir: https://127.0.0.1:14000/dir
      contact:
        - mailto:admin@example.com
